---
- hosts: shop

  vars:
    java_version: 1.7u21
    tomcat_version: 7.0.25
    tmpdir: /var/tmp
    logs: 
    - { path: /usr/local/tomcat/logs/shop-access.log, index: shop, sourcetype: access }
    - { path: /usr/local/tomcat/logs/shop-error.log, index: shop, sourcetype: error }
    - { path: /usr/local/tomcat/logs/catalina.out, index: shop, sourcetype: catalina }

  tasks:
  - name: ensure java install directory works
    action: file state=directory dest=/usr/local/java

  - name: download java
    action: get_url url=http://repo.dev.example/java-{{java_versionn}}.tgz dest={{tmpdir}}/java-{{java_versionn}}.tgz

  - name: install java
    action: command chdir=/usr/local/java tar xzf {{tmpdir}}/java-{{java_versionn}}.tgz

  - name: download tomcat
    action: get_url url=http://repo.dev.example/tomcat-{{tomcat_version}}.tar.gz dest={{tmpdir}}/tomcat-{{tomcat_version}}.tar.gz

  - name: install tomcat
    action: command chdir=/usr/local tar xzf {{tmpdir}}/tomcat-{{tomcat_version}}.tar.gz

  - name: install shop app
    action: copy src=files/shop.jar dest=/usr/local/tomcat/webapps/shop.jar
    notify: start_tomcat

  - name: set log shipping correctly
    action: template src=templates/logship.conf.tmpl dest=/usr/local/etc/shop-logship.conf
    notify: logshipper


  handlers:
  - name: logshipper
    action: debug msg="this is where the logshipper service would be restarted"

  - name: start_tomcat
    action: command /usr/local/tomcat/bin/startup.sh 
