---
- hosts: vagrant

  tasks:
  - name: add dummy host in /etc/hosts
    action: lineinfile state=present regexp=repo.dev.example line='192.168.0.1      repo.dev.example'

  - name: ensure /usr/local is writable by admin group
    action: file state=directory group=admin mode=775 dest=/usr/local
